version: "3.0"
services:
    odoo_environment:
        build: .
        container_name: "odoo_environment"
        tty: true
        volumes: 
            - ./templates/odoo_installer:/home/odoo/odoo_installer
            - ./templates/install_requirements_git_repos.sh:/home/odoo/install_requirements_git_repos.sh
            - ./config:/home/odoo/workspace/config
            - ./commands:/home/odoo/workspace/commands
            - ./libs:/home/odoo/.odooenv
            - ./odoo:/home/odoo/workspace/odoo
            - ./data_dir:/home/odoo/workspace/data_dir
            - ./addons:/home/odoo/workspace/addons
        ports:
            - 80:8069
        links: 
            - odoo_database:odoo_database
        depends_on:
            - odoo_database

    odoo_database:
        image: postgres:11
        container_name: odoo_database
        ports:
            - 5432:5432
        volumes:
            - ./database_dump:/database_dump
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_USER: odoo
