version: "2.4"
services:
    nginx_server:
        image: nginx:latest
        container_name: nginx_server
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - odoo_environment
    odoo_environment:
        build: .
        container_name: odoo_environment
        tty: true
        volumes:
            - ./addons:/home/docker/workspace/addons
            - ./config:/home/docker/workspace/config
            - ./data_dir:/home/docker/workspace/data_dir
            - python_libs:/usr/local/lib/
            - ./odoo:/home/docker/workspace/odoo
        expose:
            - "8069"
            - "8072"
        links:
            - postgres:postgres
        depends_on:
            - postgres
        environment:
            - C_FORCE_ROOT=true
        mem_reservation: 4000m
    postgres:
        image: postgres:11
        container_name: odoo_database
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
            - odoo_database_volum:/databases
            - ./dump_database:/dump_database
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_USER: odoo

volumes:
    data_dir:
    odoo_database_volum:
    python_libs:
