version: "2.4"
services:
    odoo_environment:
        build: .
        container_name: odoo_environment
        tty: true
        volumes:
            - ./addons:/home/docker/workspace/addons
            - ./config:/home/docker/workspace/config
            - data_dir:/home/docker/workspace/data_dir
            - ./odoo:/home/docker/workspace/odoo
        ports:
            - 8069:8069
        links:
            - postgres:postgres
            - ftp_server:ftp_server
        depends_on:
            - postgres
        environment:
            - C_FORCE_ROOT=true
    postgres:
        image: postgres:9.6
        container_name: odoo_database
        volumes:
            - odoo_database_volum:/databases
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_USER: odoo

    ftp_server:
        image: bogem/ftp
        container_name: ftp_server
        volumes:
          - ftp_server_volum:/home/vsftpd
        ports:
          - 20:20
          - 21:21
          - 47400-47470:47400-47470
        environment:
            FTP_USER: test
            FTP_PASS: test
            PASV_ADDRESS: 172.17.0.1

volumes:
    data_dir:
    odoo_database_volum:
    ftp_server_volum:
