version: "2.4"
services:
    odoo_environment:
        build: .
        container_name: odoo_environment
        tty: true
        volumes:
            - ./addons:/odoo/workspace/addons
            - ./config:/odoo/workspace/config
            - data_dir:/odoo/workspace/data_dir
            - odoo_addons:/odoo/workspace/odoo/addons
        ports:
            - 8069:8069
        links:
            - postgres:postgres
        depends_on:
            - postgres
        environment:
            - C_FORCE_ROOT=true
    postgres:
        image: postgres:9.6
        container_name: odoo_database
        volumes:
            - odoo_database_volum:/databases
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_USER: odoo

volumes:
    data_dir:
    odoo_database_volum:
    odoo_addons:
        driver: local
        driver_opts:
          type: none
          device: $PWD/odoo_addons
          o: bind
