version: "2.4"
services:
    odoo_environment:
        build: .
        container_name: odoo_environment
        tty: true
        volumes:
            - ./addons:/home/docker/workspace/addons
            - ./config:/home/docker/workspace/config
            - data_dir:/home/docker/workspace/data_dir
            - python_libs:/usr/local/lib/
            - ./odoo:/home/docker/workspace/odoo
        ports:
            - 80:8069
        links:
            - postgres:postgres
        depends_on:
            - postgres
        environment:
            - C_FORCE_ROOT=true
        mem_reservation: 4000m
    postgres:
        image: postgres:11
        container_name: odoo_database
        volumes:
            - odoo_database_volum:/databases
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_USER: odoo

volumes:
    data_dir:
    odoo_database_volum:
    python_libs:
